# OPENCART UPGRADE SCRIPT v1.5.x
# WWW.OPENCART.COM
# Qphoria

# DO NOT RUN THIS ENTIRE FILE MANUALLY THROUGH PHPMYADMIN OR OTHER MYSQL DB TOOL
# THIS FILE IS GENERATED FOR USE WITH THE UPGRADE.PHP SCRIPT LOCATED IN THE INSTALL FOLDER
# THE UPGRADE.PHP SCRIPT IS DESIGNED TO VERIFY THE TABLES BEFORE EXECUTING WHICH PREVENTS ERRORS

# IF YOU NEED TO MANUALLY RUN THEN YOU CAN DO IT BY INDIVIDUAL VERSIONS. EACH SECTION IS LABELED.
# BE SURE YOU CHANGE THE PREFIX "oc_" TO YOUR PREFIX OR REMOVE IT IF NOT USING A PREFIX

# Version 1.0.5

ALTER TABLE `ot_design_color` ADD `sort` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '';
ALTER TABLE `ot_printable_product_view_region` ADD `mask` varchar(255) COLLATE utf8_bin COMMENT '';
ALTER TABLE `ot_printable_product` ADD `printable_status` TINYINT(1) NULL DEFAULT '1';
ALTER TABLE `ot_printable_product_view` ADD `underfill` VARCHAR(255) NULL DEFAULT NULL;